# Generated by Django 4.2.2 on 2024-10-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="user",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="user",
        ),
    ]
