# Generated by Django 4.2.2 on 2024-10-01 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_remove_course_user_remove_lesson_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="name",
            new_name="name_course",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="name",
            new_name="name_lesson",
        ),
    ]
