# Generated by Django 4.2.2 on 2024-10-01 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_rename_name_course_name_course_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="name_course",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="name_lesson",
            new_name="name",
        ),
    ]
